development:
  adapter: postgresql
  database: cease_and_desist_development
  encoding: utf8
  host: localhost
  pool: 5
  
test:
  adapter: postgresql
  database: cease_and_desist_test
  encoding: utf8
  host: localhost
  pool: 5
